numServers: 3
numClients: 6

debug: false
persist: false

clientRequestTimeout: 1500ms

fd:
  pullInterval: 200ms
  timeout: 100ms

mailboxes:
  receiveChanSize: 10000
  dialTimeout: 50ms
  readTimeout: 50ms
  writeTimeout: 50ms

leaderElection:
  timeout: 150ms
  timeoutOffset: 150ms

appendEntriesSendInterval: 1ms
sharedResourceTimeout: 1ms
inputChanReadTimeout: 1ms

servers:
  1:
    mailboxAddr: "localhost:4001"
    monitorAddr: "localhost:5001"
  2:
    mailboxAddr: "localhost:4002"
    monitorAddr: "localhost:5002"
  3:
    mailboxAddr: "localhost:4003"
    monitorAddr: "localhost:5003"

clients:
  1:
    mailboxAddr: "localhost:4019"

  2:
    mailboxAddr: "localhost:4020"

  3:
    mailboxAddr: "localhost:4021"

  4:
    mailboxAddr: "localhost:4022"

  5:
    mailboxAddr: "localhost:4023"

  6:
    mailboxAddr: "localhost:4024"

