numServers: 5
numClients: 1

debug: true

persist: false

clientRequestTimeout: 1000ms

fd:
  pullInterval: 300ms
  timeout: 150ms

mailboxes:
  receiveChanSize: 10000
  dialTimeout: 100ms
  readTimeout: 100ms
  writeTimeout: 100ms

leaderElection:
  timeout: 150ms
  timeoutOffset: 150ms

appendEntriesSendInterval: 5ms

sharedResourceTimeout: 2ms

inputChanReadTimeout: 2ms

servers:
  1:
    mailboxAddr: "localhost:8001"
    monitorAddr: "localhost:9001"

  2:
    mailboxAddr: "localhost:8002"
    monitorAddr: "localhost:9002"

  3:
    mailboxAddr: "localhost:8003"
    monitorAddr: "localhost:9003"

  4:
    mailboxAddr: "localhost:8004"
    monitorAddr: "localhost:9004"

  5:
    mailboxAddr: "localhost:8005"
    monitorAddr: "localhost:9005"

clients:
  1:
    mailboxAddr: "localhost:8019"
